// Generated by scripts/build-config.js — do not edit by hand in production.
window.NOVA_CONFIG = {
  "provider": "mock",
  "supabaseUrl": "",
  "supabaseKey": "",
  "organisationId": "00000000-0000-0000-0000-000000000001"
};
