-- Nova Org Supabase schema
-- Run in the Supabase SQL editor, then create a user through Supabase Auth.
create extension if not exists pgcrypto;

create table if not exists public.organisations (
 id uuid primary key default gen_random_uuid(), slug text not null unique, name text not null,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.organisation_members (
 organisation_id uuid not null references public.organisations(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade,
 role text not null check (role in ('owner','admin','manager','tutor','finance')),
 active boolean not null default true, created_at timestamptz not null default now(),
 primary key (organisation_id,user_id)
);
create table if not exists public.families (
 id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade,
 reference_code text not null, parent_name text not null, payment_type text, qualifying_period text,
 invoice_day smallint, statement_day smallint, expected_payment_day smallint, expected_payment_next_month boolean not null default false,
 linked_student_names text, status text not null default 'active', phone text, email text, address text, notes text,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organisation_id,reference_code)
);
create table if not exists public.students (
 id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade,
 family_id uuid references public.families(id) on delete set null, reference_code text not null, full_name text not null,
 programme text, attendance_days text[] not null default '{}', session_time text, room_allocation text, status text not null default 'active',
 year_group text, date_of_birth date, school text, support_needs text, notes text,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organisation_id,reference_code)
);
create table if not exists public.staff (
 id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade,
 reference_code text not null, full_name text not null, is_teacher boolean not null default false, is_manager boolean not null default false,
 programme text, responsibilities text, working_hours_pattern text, missing_details text, status text not null default 'active',
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organisation_id,reference_code)
);
create table if not exists public.rooms (
 id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade,
 reference_code text not null, name text not null, room_type text, primary_use text, programme text, availability text,
 status text not null default 'active', notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(organisation_id,reference_code)
);
create table if not exists public.schedules (
 id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade,
 reference_code text not null, day_name text not null, centre_purpose text, teaching_time text, staff_hours text, programme_rooms text, notes text,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organisation_id,reference_code)
);
create table if not exists public.uc_claims (
 id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade,
 family_id uuid references public.families(id) on delete cascade, reference_code text not null, qualifying_period text,
 invoice_day smallint, statement_day smallint, expected_payment_day smallint, expected_payment_next_month boolean not null default false,
 claim_month date, invoice_amount numeric(10,2), submitted_at timestamptz, actual_payment_date date, amount_received numeric(10,2),
 status text not null default 'upcoming', notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(organisation_id,reference_code)
);
create table if not exists public.tasks (
 id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade,
 title text not null, notes text, owner_name text, priority text not null default 'medium', due_date date,
 status text not null default 'open' check(status in ('open','in_progress','completed','cancelled')), completed_at timestamptz,
 related_type text, related_id uuid, created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.calendar_events (
 id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade,
 title text not null, notes text, category text not null default 'general', start_at timestamptz not null, end_at timestamptz,
 all_day boolean not null default false, recurrence_rule text, related_type text, related_id uuid,
 created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.audit_logs (
 id bigint generated always as identity primary key, organisation_id uuid not null references public.organisations(id) on delete cascade,
 actor_id uuid references auth.users(id), action text not null, table_name text not null, record_id text, before_data jsonb, after_data jsonb,
 created_at timestamptz not null default now()
);

create index if not exists idx_families_org on public.families(organisation_id);
create index if not exists idx_students_org_family on public.students(organisation_id,family_id);
create index if not exists idx_tasks_org_due on public.tasks(organisation_id,due_date,status);
create index if not exists idx_events_org_start on public.calendar_events(organisation_id,start_at);
create index if not exists idx_claims_org_days on public.uc_claims(organisation_id,invoice_day,statement_day,expected_payment_day);

create or replace function public.is_org_member(org uuid) returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.organisation_members m where m.organisation_id=org and m.user_id=auth.uid() and m.active=true)
$$;
create or replace function public.can_manage_org(org uuid) returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.organisation_members m where m.organisation_id=org and m.user_id=auth.uid() and m.active=true and m.role in ('owner','admin','manager'))
$$;

alter table public.organisations enable row level security;
alter table public.organisation_members enable row level security;
alter table public.families enable row level security;
alter table public.students enable row level security;
alter table public.staff enable row level security;
alter table public.rooms enable row level security;
alter table public.schedules enable row level security;
alter table public.uc_claims enable row level security;
alter table public.tasks enable row level security;
alter table public.calendar_events enable row level security;
alter table public.audit_logs enable row level security;

create policy "members read organisations" on public.organisations for select to authenticated using(public.is_org_member(id));
create policy "members read memberships" on public.organisation_members for select to authenticated using(public.is_org_member(organisation_id));
create policy "owners manage memberships" on public.organisation_members for all to authenticated using(public.can_manage_org(organisation_id)) with check(public.can_manage_org(organisation_id));

-- Apply consistent organisation policies to operational tables.
do $$ declare t text; begin
 foreach t in array array['families','students','staff','rooms','schedules','uc_claims','tasks','calendar_events','audit_logs'] loop
  execute format('create policy "members read %1$s" on public.%1$I for select to authenticated using(public.is_org_member(organisation_id))',t);
  execute format('create policy "managers write %1$s" on public.%1$I for insert to authenticated with check(public.can_manage_org(organisation_id))',t);
  execute format('create policy "managers update %1$s" on public.%1$I for update to authenticated using(public.can_manage_org(organisation_id)) with check(public.can_manage_org(organisation_id))',t);
  execute format('create policy "managers delete %1$s" on public.%1$I for delete to authenticated using(public.can_manage_org(organisation_id))',t);
 end loop;
exception when duplicate_object then null; end $$;

insert into public.organisations(id,slug,name) values ('00000000-0000-0000-0000-000000000001','nova','Nova Education') on conflict(id) do update set name=excluded.name;

-- After creating your first Supabase Auth user, run this with their UUID:
-- insert into public.organisation_members(organisation_id,user_id,role) values ('00000000-0000-0000-0000-000000000001','YOUR-AUTH-USER-UUID','owner');


-- Current Nova seed data
insert into public.families(organisation_id,reference_code,parent_name,payment_type,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,linked_student_names,status) values ('00000000-0000-0000-0000-000000000001','FAM001','Ahmed Abdulrahman','Universal Credit','11th–10th',10,13,17,false,'Mohammed Abdulrahman','active') on conflict(organisation_id,reference_code) do update set parent_name=excluded.parent_name,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,linked_student_names=excluded.linked_student_names;
insert into public.families(organisation_id,reference_code,parent_name,payment_type,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,linked_student_names,status) values ('00000000-0000-0000-0000-000000000001','FAM002','Marafee Omar','Universal Credit','28th–27th',27,30,3,true,'Zaynab Al-Ashai; Magda Al-Ashai; Faiza Al-Ashai','active') on conflict(organisation_id,reference_code) do update set parent_name=excluded.parent_name,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,linked_student_names=excluded.linked_student_names;
insert into public.families(organisation_id,reference_code,parent_name,payment_type,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,linked_student_names,status) values ('00000000-0000-0000-0000-000000000001','FAM003','Tracy Pater','Universal Credit','9th–8th',8,11,15,false,'Elijah Martina; Alyaa Martina','active') on conflict(organisation_id,reference_code) do update set parent_name=excluded.parent_name,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,linked_student_names=excluded.linked_student_names;
insert into public.families(organisation_id,reference_code,parent_name,payment_type,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,linked_student_names,status) values ('00000000-0000-0000-0000-000000000001','FAM004','Sahana Begum','Universal Credit','1st–30th',30,3,7,false,'Aisha; Saif','active') on conflict(organisation_id,reference_code) do update set parent_name=excluded.parent_name,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,linked_student_names=excluded.linked_student_names;
insert into public.families(organisation_id,reference_code,parent_name,payment_type,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,linked_student_names,status) values ('00000000-0000-0000-0000-000000000001','FAM005','Afrah Ibrahim','Universal Credit','12th–11th',11,14,18,false,'Rudaina; Yazeed; Leena','active') on conflict(organisation_id,reference_code) do update set parent_name=excluded.parent_name,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,linked_student_names=excluded.linked_student_names;
insert into public.families(organisation_id,reference_code,parent_name,payment_type,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,linked_student_names,status) values ('00000000-0000-0000-0000-000000000001','FAM006','Angelina Fosu','Universal Credit','7th–6th',6,9,13,false,'Daniel Manu','active') on conflict(organisation_id,reference_code) do update set parent_name=excluded.parent_name,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,linked_student_names=excluded.linked_student_names;
insert into public.families(organisation_id,reference_code,parent_name,payment_type,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,linked_student_names,status) values ('00000000-0000-0000-0000-000000000001','FAM007','Nadeem Ahmed','Universal Credit','26th–25th',25,28,1,true,'C''yaan Amreen','active') on conflict(organisation_id,reference_code) do update set parent_name=excluded.parent_name,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,linked_student_names=excluded.linked_student_names;
insert into public.families(organisation_id,reference_code,parent_name,payment_type,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,linked_student_names,status) values ('00000000-0000-0000-0000-000000000001','FAM008','Jamaad Mohamoud','Universal Credit','1st–30th',30,3,7,false,'Not yet provided','active') on conflict(organisation_id,reference_code) do update set parent_name=excluded.parent_name,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,linked_student_names=excluded.linked_student_names;
insert into public.families(organisation_id,reference_code,parent_name,payment_type,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,linked_student_names,status) values ('00000000-0000-0000-0000-000000000001','FAM009','Motasim Abbas','Universal Credit','1st–30th',30,3,7,false,'Not yet provided','active') on conflict(organisation_id,reference_code) do update set parent_name=excluded.parent_name,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,linked_student_names=excluded.linked_student_names;
insert into public.families(organisation_id,reference_code,parent_name,payment_type,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,linked_student_names,status) values ('00000000-0000-0000-0000-000000000001','FAM010','Salma Ishak','Universal Credit','5th–4th',4,7,11,false,'Not yet provided','active') on conflict(organisation_id,reference_code) do update set parent_name=excluded.parent_name,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,linked_student_names=excluded.linked_student_names;
insert into public.families(organisation_id,reference_code,parent_name,payment_type,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,linked_student_names,status) values ('00000000-0000-0000-0000-000000000001','FAM011','Aysha Iqbal','Universal Credit','7th–6th',6,9,13,false,'Not yet provided','active') on conflict(organisation_id,reference_code) do update set parent_name=excluded.parent_name,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,linked_student_names=excluded.linked_student_names;
insert into public.families(organisation_id,reference_code,parent_name,payment_type,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,linked_student_names,status) values ('00000000-0000-0000-0000-000000000001','FAM012','Eman Muhammed','Universal Credit','7th–6th',6,9,13,false,'Not yet provided','active') on conflict(organisation_id,reference_code) do update set parent_name=excluded.parent_name,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,linked_student_names=excluded.linked_student_names;
insert into public.families(organisation_id,reference_code,parent_name,payment_type,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,linked_student_names,status) values ('00000000-0000-0000-0000-000000000001','FAM013','Gehan Sedahmed','Universal Credit','9th–8th',8,11,15,false,'Not yet provided','active') on conflict(organisation_id,reference_code) do update set parent_name=excluded.parent_name,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,linked_student_names=excluded.linked_student_names;
insert into public.families(organisation_id,reference_code,parent_name,payment_type,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,linked_student_names,status) values ('00000000-0000-0000-0000-000000000001','FAM014','Abda Elbushra','Universal Credit','9th–8th',8,11,15,false,'Not yet provided','active') on conflict(organisation_id,reference_code) do update set parent_name=excluded.parent_name,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,linked_student_names=excluded.linked_student_names;
insert into public.families(organisation_id,reference_code,parent_name,payment_type,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,linked_student_names,status) values ('00000000-0000-0000-0000-000000000001','FAM015','Akhtar Hussain','Universal Credit','17th–16th',16,19,23,false,'Not yet provided','active') on conflict(organisation_id,reference_code) do update set parent_name=excluded.parent_name,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,linked_student_names=excluded.linked_student_names;
insert into public.students(organisation_id,family_id,reference_code,full_name,programme,attendance_days,session_time,room_allocation,status,notes) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM001'),'STU001','Mohammed Abdulrahman','PreNova',array['Monday','Tuesday']::text[],'17:00–20:00','Room 3','active',null) on conflict(organisation_id,reference_code) do update set full_name=excluded.full_name,family_id=excluded.family_id,programme=excluded.programme,attendance_days=excluded.attendance_days,session_time=excluded.session_time,room_allocation=excluded.room_allocation,notes=excluded.notes;
insert into public.students(organisation_id,family_id,reference_code,full_name,programme,attendance_days,session_time,room_allocation,status,notes) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM002'),'STU002','Zaynab Al-Ashai','PreNova',array['Monday','Saturday','Sunday']::text[],'Mon 17:00–20:00; weekends 12:00–15:00','Room 3','active',null) on conflict(organisation_id,reference_code) do update set full_name=excluded.full_name,family_id=excluded.family_id,programme=excluded.programme,attendance_days=excluded.attendance_days,session_time=excluded.session_time,room_allocation=excluded.room_allocation,notes=excluded.notes;
insert into public.students(organisation_id,family_id,reference_code,full_name,programme,attendance_days,session_time,room_allocation,status,notes) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM002'),'STU003','Magda Al-Ashai','PreNova',array['Monday','Saturday','Sunday']::text[],'Mon 17:00–20:00; weekends 12:00–15:00','Room 3','active',null) on conflict(organisation_id,reference_code) do update set full_name=excluded.full_name,family_id=excluded.family_id,programme=excluded.programme,attendance_days=excluded.attendance_days,session_time=excluded.session_time,room_allocation=excluded.room_allocation,notes=excluded.notes;
insert into public.students(organisation_id,family_id,reference_code,full_name,programme,attendance_days,session_time,room_allocation,status,notes) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM002'),'STU004','Faiza Al-Ashai','SuperNova',array['Monday','Saturday','Sunday']::text[],'Mon 17:00–20:00; weekends 12:00–15:00','Rooms 4–6','active',null) on conflict(organisation_id,reference_code) do update set full_name=excluded.full_name,family_id=excluded.family_id,programme=excluded.programme,attendance_days=excluded.attendance_days,session_time=excluded.session_time,room_allocation=excluded.room_allocation,notes=excluded.notes;
insert into public.students(organisation_id,family_id,reference_code,full_name,programme,attendance_days,session_time,room_allocation,status,notes) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM003'),'STU005','Elijah Martina','SuperNova',array['Sunday']::text[],'12:00–15:00','Rooms 4–6','active',null) on conflict(organisation_id,reference_code) do update set full_name=excluded.full_name,family_id=excluded.family_id,programme=excluded.programme,attendance_days=excluded.attendance_days,session_time=excluded.session_time,room_allocation=excluded.room_allocation,notes=excluded.notes;
insert into public.students(organisation_id,family_id,reference_code,full_name,programme,attendance_days,session_time,room_allocation,status,notes) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM003'),'STU006','Alyaa Martina','SuperNova',array['Sunday']::text[],'12:00–15:00','Rooms 4–6','active',null) on conflict(organisation_id,reference_code) do update set full_name=excluded.full_name,family_id=excluded.family_id,programme=excluded.programme,attendance_days=excluded.attendance_days,session_time=excluded.session_time,room_allocation=excluded.room_allocation,notes=excluded.notes;
insert into public.students(organisation_id,family_id,reference_code,full_name,programme,attendance_days,session_time,room_allocation,status,notes) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM004'),'STU007','Aisha','PreNova',array['Saturday']::text[],'12:00–15:00','Room 3','active','Surname not yet provided') on conflict(organisation_id,reference_code) do update set full_name=excluded.full_name,family_id=excluded.family_id,programme=excluded.programme,attendance_days=excluded.attendance_days,session_time=excluded.session_time,room_allocation=excluded.room_allocation,notes=excluded.notes;
insert into public.students(organisation_id,family_id,reference_code,full_name,programme,attendance_days,session_time,room_allocation,status,notes) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM004'),'STU008','Saif','PreNova',array['Saturday']::text[],'12:00–15:00','Room 3','active','Surname not yet provided') on conflict(organisation_id,reference_code) do update set full_name=excluded.full_name,family_id=excluded.family_id,programme=excluded.programme,attendance_days=excluded.attendance_days,session_time=excluded.session_time,room_allocation=excluded.room_allocation,notes=excluded.notes;
insert into public.students(organisation_id,family_id,reference_code,full_name,programme,attendance_days,session_time,room_allocation,status,notes) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM005'),'STU009','Rudaina','SuperNova','{}'::text[],'Not yet provided','Rooms 4–6','active','Surname not yet provided') on conflict(organisation_id,reference_code) do update set full_name=excluded.full_name,family_id=excluded.family_id,programme=excluded.programme,attendance_days=excluded.attendance_days,session_time=excluded.session_time,room_allocation=excluded.room_allocation,notes=excluded.notes;
insert into public.students(organisation_id,family_id,reference_code,full_name,programme,attendance_days,session_time,room_allocation,status,notes) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM005'),'STU010','Yazeed','SuperNova','{}'::text[],'Not yet provided','Rooms 4–6','active','Surname not yet provided') on conflict(organisation_id,reference_code) do update set full_name=excluded.full_name,family_id=excluded.family_id,programme=excluded.programme,attendance_days=excluded.attendance_days,session_time=excluded.session_time,room_allocation=excluded.room_allocation,notes=excluded.notes;
insert into public.students(organisation_id,family_id,reference_code,full_name,programme,attendance_days,session_time,room_allocation,status,notes) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM005'),'STU011','Leena','PreNova','{}'::text[],'Not yet provided','Room 3','active','Surname not yet provided') on conflict(organisation_id,reference_code) do update set full_name=excluded.full_name,family_id=excluded.family_id,programme=excluded.programme,attendance_days=excluded.attendance_days,session_time=excluded.session_time,room_allocation=excluded.room_allocation,notes=excluded.notes;
insert into public.students(organisation_id,family_id,reference_code,full_name,programme,attendance_days,session_time,room_allocation,status,notes) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM006'),'STU012','Daniel Manu','PreNova','{}'::text[],'Not yet provided','Room 3','active',null) on conflict(organisation_id,reference_code) do update set full_name=excluded.full_name,family_id=excluded.family_id,programme=excluded.programme,attendance_days=excluded.attendance_days,session_time=excluded.session_time,room_allocation=excluded.room_allocation,notes=excluded.notes;
insert into public.students(organisation_id,family_id,reference_code,full_name,programme,attendance_days,session_time,room_allocation,status,notes) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM007'),'STU013','C''yaan Amreen','PreNova','{}'::text[],'Not yet provided','Room 3','active',null) on conflict(organisation_id,reference_code) do update set full_name=excluded.full_name,family_id=excluded.family_id,programme=excluded.programme,attendance_days=excluded.attendance_days,session_time=excluded.session_time,room_allocation=excluded.room_allocation,notes=excluded.notes;
insert into public.staff(organisation_id,reference_code,full_name,is_teacher,is_manager,programme,responsibilities,working_hours_pattern,missing_details) values ('00000000-0000-0000-0000-000000000001','S01','Zain Gul',true,true,'SuperNova','Teaching, entry, exit and centre oversight','Mon–Thu 15:00–21:00; Fri 09:00–21:00; Sat–Sun 09:00–17:00','Assigned days, pay, compliance') on conflict(organisation_id,reference_code) do update set full_name=excluded.full_name,programme=excluded.programme,responsibilities=excluded.responsibilities,working_hours_pattern=excluded.working_hours_pattern,missing_details=excluded.missing_details;
insert into public.staff(organisation_id,reference_code,full_name,is_teacher,is_manager,programme,responsibilities,working_hours_pattern,missing_details) values ('00000000-0000-0000-0000-000000000001','S02','Ibraheem Ridhwaan',true,true,'PreNova','Teaching, entry, exit and centre oversight','General staff-hours pattern','Assigned days, pay, compliance') on conflict(organisation_id,reference_code) do update set full_name=excluded.full_name,programme=excluded.programme,responsibilities=excluded.responsibilities,working_hours_pattern=excluded.working_hours_pattern,missing_details=excluded.missing_details;
insert into public.staff(organisation_id,reference_code,full_name,is_teacher,is_manager,programme,responsibilities,working_hours_pattern,missing_details) values ('00000000-0000-0000-0000-000000000001','S03','Amina Chebel',true,false,'PreNova','Teaching','General staff-hours pattern','Assigned days, pay, compliance') on conflict(organisation_id,reference_code) do update set full_name=excluded.full_name,programme=excluded.programme,responsibilities=excluded.responsibilities,working_hours_pattern=excluded.working_hours_pattern,missing_details=excluded.missing_details;
insert into public.staff(organisation_id,reference_code,full_name,is_teacher,is_manager,programme,responsibilities,working_hours_pattern,missing_details) values ('00000000-0000-0000-0000-000000000001','S04','Dalia Chebel',true,false,'PreNova','Teaching','General staff-hours pattern','Assigned days, pay, compliance') on conflict(organisation_id,reference_code) do update set full_name=excluded.full_name,programme=excluded.programme,responsibilities=excluded.responsibilities,working_hours_pattern=excluded.working_hours_pattern,missing_details=excluded.missing_details;
insert into public.staff(organisation_id,reference_code,full_name,is_teacher,is_manager,programme,responsibilities,working_hours_pattern,missing_details) values ('00000000-0000-0000-0000-000000000001','S05','Fahmida',true,false,'PreNova','Teaching','General staff-hours pattern','Full name, assigned days, pay, compliance') on conflict(organisation_id,reference_code) do update set full_name=excluded.full_name,programme=excluded.programme,responsibilities=excluded.responsibilities,working_hours_pattern=excluded.working_hours_pattern,missing_details=excluded.missing_details;
insert into public.staff(organisation_id,reference_code,full_name,is_teacher,is_manager,programme,responsibilities,working_hours_pattern,missing_details) values ('00000000-0000-0000-0000-000000000001','S06','Faiza',true,false,'PreNova','Teaching','General staff-hours pattern','Full name, assigned days, pay, compliance') on conflict(organisation_id,reference_code) do update set full_name=excluded.full_name,programme=excluded.programme,responsibilities=excluded.responsibilities,working_hours_pattern=excluded.working_hours_pattern,missing_details=excluded.missing_details;
insert into public.staff(organisation_id,reference_code,full_name,is_teacher,is_manager,programme,responsibilities,working_hours_pattern,missing_details) values ('00000000-0000-0000-0000-000000000001','S07','Aisha Hassan',true,false,'PreNova','Teaching','General staff-hours pattern','Assigned days, pay, compliance') on conflict(organisation_id,reference_code) do update set full_name=excluded.full_name,programme=excluded.programme,responsibilities=excluded.responsibilities,working_hours_pattern=excluded.working_hours_pattern,missing_details=excluded.missing_details;
insert into public.staff(organisation_id,reference_code,full_name,is_teacher,is_manager,programme,responsibilities,working_hours_pattern,missing_details) values ('00000000-0000-0000-0000-000000000001','S08','Tahreem Abbas',true,false,'PreNova','Teaching','General staff-hours pattern','Assigned days, pay, compliance') on conflict(organisation_id,reference_code) do update set full_name=excluded.full_name,programme=excluded.programme,responsibilities=excluded.responsibilities,working_hours_pattern=excluded.working_hours_pattern,missing_details=excluded.missing_details;
insert into public.rooms(organisation_id,reference_code,name,room_type,primary_use,programme,availability,status,notes) values ('00000000-0000-0000-0000-000000000001','R01','Room 1','Meeting / manager room','Meetings, registrations, onboarding and on-site manager use','General','Mainly Friday; outside teaching as required','active',null) on conflict(organisation_id,reference_code) do update set name=excluded.name,room_type=excluded.room_type,primary_use=excluded.primary_use,programme=excluded.programme,availability=excluded.availability,notes=excluded.notes;
insert into public.rooms(organisation_id,reference_code,name,room_type,primary_use,programme,availability,status,notes) values ('00000000-0000-0000-0000-000000000001','R02','Room 2','Games room','Games, recreation and student break activities','General','During centre sessions','active','Recent change') on conflict(organisation_id,reference_code) do update set name=excluded.name,room_type=excluded.room_type,primary_use=excluded.primary_use,programme=excluded.programme,availability=excluded.availability,notes=excluded.notes;
insert into public.rooms(organisation_id,reference_code,name,room_type,primary_use,programme,availability,status,notes) values ('00000000-0000-0000-0000-000000000001','R03','Room 3','PreNova room','Nursery to Year 6 and 11+ teaching','PreNova','Mon–Thu 17:00–20:00; Sat–Sun 12:00–15:00','active',null) on conflict(organisation_id,reference_code) do update set name=excluded.name,room_type=excluded.room_type,primary_use=excluded.primary_use,programme=excluded.programme,availability=excluded.availability,notes=excluded.notes;
insert into public.rooms(organisation_id,reference_code,name,room_type,primary_use,programme,availability,status,notes) values ('00000000-0000-0000-0000-000000000001','R04','Room 4','SuperNova room A','Year 7 to Year 11 teaching','SuperNova','Mon–Thu 17:00–20:00; Sat–Sun 12:00–15:00','active','Primary room') on conflict(organisation_id,reference_code) do update set name=excluded.name,room_type=excluded.room_type,primary_use=excluded.primary_use,programme=excluded.programme,availability=excluded.availability,notes=excluded.notes;
insert into public.rooms(organisation_id,reference_code,name,room_type,primary_use,programme,availability,status,notes) values ('00000000-0000-0000-0000-000000000001','R05','Room 5','SuperNova room B','Overflow when Room 4 is full','SuperNova','Same teaching sessions','active',null) on conflict(organisation_id,reference_code) do update set name=excluded.name,room_type=excluded.room_type,primary_use=excluded.primary_use,programme=excluded.programme,availability=excluded.availability,notes=excluded.notes;
insert into public.rooms(organisation_id,reference_code,name,room_type,primary_use,programme,availability,status,notes) values ('00000000-0000-0000-0000-000000000001','R06','Room 6','SuperNova room C','Additional SuperNova capacity','SuperNova','Same teaching sessions','active',null) on conflict(organisation_id,reference_code) do update set name=excluded.name,room_type=excluded.room_type,primary_use=excluded.primary_use,programme=excluded.programme,availability=excluded.availability,notes=excluded.notes;
insert into public.rooms(organisation_id,reference_code,name,room_type,primary_use,programme,availability,status,notes) values ('00000000-0000-0000-0000-000000000001','LOB','Lobby','Shared space','Reception, waiting, staff and general session use','General','All centre sessions','active',null) on conflict(organisation_id,reference_code) do update set name=excluded.name,room_type=excluded.room_type,primary_use=excluded.primary_use,programme=excluded.programme,availability=excluded.availability,notes=excluded.notes;
insert into public.schedules(organisation_id,reference_code,day_name,centre_purpose,teaching_time,staff_hours,programme_rooms,notes) values ('00000000-0000-0000-0000-000000000001','SCH01','Monday','Teaching sessions','17:00–20:00','15:00–21:00','PreNova Room 3; SuperNova Rooms 4–6','Concurrent classes') on conflict(organisation_id,reference_code) do update set day_name=excluded.day_name,centre_purpose=excluded.centre_purpose,teaching_time=excluded.teaching_time,staff_hours=excluded.staff_hours,programme_rooms=excluded.programme_rooms,notes=excluded.notes;
insert into public.schedules(organisation_id,reference_code,day_name,centre_purpose,teaching_time,staff_hours,programme_rooms,notes) values ('00000000-0000-0000-0000-000000000001','SCH02','Tuesday','Teaching sessions','17:00–20:00','15:00–21:00','PreNova Room 3; SuperNova Rooms 4–6','Concurrent classes') on conflict(organisation_id,reference_code) do update set day_name=excluded.day_name,centre_purpose=excluded.centre_purpose,teaching_time=excluded.teaching_time,staff_hours=excluded.staff_hours,programme_rooms=excluded.programme_rooms,notes=excluded.notes;
insert into public.schedules(organisation_id,reference_code,day_name,centre_purpose,teaching_time,staff_hours,programme_rooms,notes) values ('00000000-0000-0000-0000-000000000001','SCH03','Wednesday','Teaching sessions','17:00–20:00','15:00–21:00','PreNova Room 3; SuperNova Rooms 4–6','Concurrent classes') on conflict(organisation_id,reference_code) do update set day_name=excluded.day_name,centre_purpose=excluded.centre_purpose,teaching_time=excluded.teaching_time,staff_hours=excluded.staff_hours,programme_rooms=excluded.programme_rooms,notes=excluded.notes;
insert into public.schedules(organisation_id,reference_code,day_name,centre_purpose,teaching_time,staff_hours,programme_rooms,notes) values ('00000000-0000-0000-0000-000000000001','SCH04','Thursday','Teaching sessions','17:00–20:00','15:00–21:00','PreNova Room 3; SuperNova Rooms 4–6','Concurrent classes') on conflict(organisation_id,reference_code) do update set day_name=excluded.day_name,centre_purpose=excluded.centre_purpose,teaching_time=excluded.teaching_time,staff_hours=excluded.staff_hours,programme_rooms=excluded.programme_rooms,notes=excluded.notes;
insert into public.schedules(organisation_id,reference_code,day_name,centre_purpose,teaching_time,staff_hours,programme_rooms,notes) values ('00000000-0000-0000-0000-000000000001','SCH05','Friday','Meetings, registrations and onboarding','No regular teaching','09:00–21:00','Mainly Room 1',null) on conflict(organisation_id,reference_code) do update set day_name=excluded.day_name,centre_purpose=excluded.centre_purpose,teaching_time=excluded.teaching_time,staff_hours=excluded.staff_hours,programme_rooms=excluded.programme_rooms,notes=excluded.notes;
insert into public.schedules(organisation_id,reference_code,day_name,centre_purpose,teaching_time,staff_hours,programme_rooms,notes) values ('00000000-0000-0000-0000-000000000001','SCH06','Saturday','Teaching sessions','12:00–15:00','09:00–17:00','PreNova Room 3; SuperNova Rooms 4–6','Concurrent classes') on conflict(organisation_id,reference_code) do update set day_name=excluded.day_name,centre_purpose=excluded.centre_purpose,teaching_time=excluded.teaching_time,staff_hours=excluded.staff_hours,programme_rooms=excluded.programme_rooms,notes=excluded.notes;
insert into public.schedules(organisation_id,reference_code,day_name,centre_purpose,teaching_time,staff_hours,programme_rooms,notes) values ('00000000-0000-0000-0000-000000000001','SCH07','Sunday','Teaching sessions','12:00–15:00','09:00–17:00','PreNova Room 3; SuperNova Rooms 4–6','Concurrent classes') on conflict(organisation_id,reference_code) do update set day_name=excluded.day_name,centre_purpose=excluded.centre_purpose,teaching_time=excluded.teaching_time,staff_hours=excluded.staff_hours,programme_rooms=excluded.programme_rooms,notes=excluded.notes;
insert into public.uc_claims(organisation_id,family_id,reference_code,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,status) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM001'),'UCC001','11th–10th',10,13,17,false,'upcoming') on conflict(organisation_id,reference_code) do update set family_id=excluded.family_id,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,status=excluded.status;
insert into public.uc_claims(organisation_id,family_id,reference_code,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,status) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM002'),'UCC002','28th–27th',27,30,3,true,'upcoming') on conflict(organisation_id,reference_code) do update set family_id=excluded.family_id,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,status=excluded.status;
insert into public.uc_claims(organisation_id,family_id,reference_code,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,status) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM003'),'UCC003','9th–8th',8,11,15,false,'upcoming') on conflict(organisation_id,reference_code) do update set family_id=excluded.family_id,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,status=excluded.status;
insert into public.uc_claims(organisation_id,family_id,reference_code,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,status) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM004'),'UCC004','1st–30th',30,3,7,false,'upcoming') on conflict(organisation_id,reference_code) do update set family_id=excluded.family_id,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,status=excluded.status;
insert into public.uc_claims(organisation_id,family_id,reference_code,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,status) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM005'),'UCC005','12th–11th',11,14,18,false,'upcoming') on conflict(organisation_id,reference_code) do update set family_id=excluded.family_id,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,status=excluded.status;
insert into public.uc_claims(organisation_id,family_id,reference_code,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,status) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM006'),'UCC006','7th–6th',6,9,13,false,'upcoming') on conflict(organisation_id,reference_code) do update set family_id=excluded.family_id,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,status=excluded.status;
insert into public.uc_claims(organisation_id,family_id,reference_code,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,status) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM007'),'UCC007','26th–25th',25,28,1,true,'upcoming') on conflict(organisation_id,reference_code) do update set family_id=excluded.family_id,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,status=excluded.status;
insert into public.uc_claims(organisation_id,family_id,reference_code,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,status) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM008'),'UCC008','1st–30th',30,3,7,false,'upcoming') on conflict(organisation_id,reference_code) do update set family_id=excluded.family_id,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,status=excluded.status;
insert into public.uc_claims(organisation_id,family_id,reference_code,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,status) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM009'),'UCC009','1st–30th',30,3,7,false,'upcoming') on conflict(organisation_id,reference_code) do update set family_id=excluded.family_id,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,status=excluded.status;
insert into public.uc_claims(organisation_id,family_id,reference_code,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,status) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM010'),'UCC010','5th–4th',4,7,11,false,'upcoming') on conflict(organisation_id,reference_code) do update set family_id=excluded.family_id,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,status=excluded.status;
insert into public.uc_claims(organisation_id,family_id,reference_code,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,status) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM011'),'UCC011','7th–6th',6,9,13,false,'upcoming') on conflict(organisation_id,reference_code) do update set family_id=excluded.family_id,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,status=excluded.status;
insert into public.uc_claims(organisation_id,family_id,reference_code,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,status) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM012'),'UCC012','7th–6th',6,9,13,false,'upcoming') on conflict(organisation_id,reference_code) do update set family_id=excluded.family_id,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,status=excluded.status;
insert into public.uc_claims(organisation_id,family_id,reference_code,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,status) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM013'),'UCC013','9th–8th',8,11,15,false,'upcoming') on conflict(organisation_id,reference_code) do update set family_id=excluded.family_id,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,status=excluded.status;
insert into public.uc_claims(organisation_id,family_id,reference_code,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,status) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM014'),'UCC014','9th–8th',8,11,15,false,'upcoming') on conflict(organisation_id,reference_code) do update set family_id=excluded.family_id,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,status=excluded.status;
insert into public.uc_claims(organisation_id,family_id,reference_code,qualifying_period,invoice_day,statement_day,expected_payment_day,expected_payment_next_month,status) values ('00000000-0000-0000-0000-000000000001',(select id from public.families where organisation_id='00000000-0000-0000-0000-000000000001' and reference_code='FAM015'),'UCC015','17th–16th',16,19,23,false,'upcoming') on conflict(organisation_id,reference_code) do update set family_id=excluded.family_id,qualifying_period=excluded.qualifying_period,invoice_day=excluded.invoice_day,statement_day=excluded.statement_day,expected_payment_day=excluded.expected_payment_day,status=excluded.status;
insert into public.tasks(organisation_id,title,notes,owner_name,priority,due_date,status) select '00000000-0000-0000-0000-000000000001','Provide standard UC monthly amount','Standard monthly fee','Families','high',current_date+1,'open' where not exists(select 1 from public.tasks where organisation_id='00000000-0000-0000-0000-000000000001' and title='Provide standard UC monthly amount' and notes='Standard monthly fee');
insert into public.tasks(organisation_id,title,notes,owner_name,priority,due_date,status) select '00000000-0000-0000-0000-000000000001','Add contact details','Phone, email and address','Families','medium',current_date+2,'open' where not exists(select 1 from public.tasks where organisation_id='00000000-0000-0000-0000-000000000001' and title='Add contact details' and notes='Phone, email and address');
insert into public.tasks(organisation_id,title,notes,owner_name,priority,due_date,status) select '00000000-0000-0000-0000-000000000001','Provide children for each parent','Student names and links','Students','high',current_date+3,'open' where not exists(select 1 from public.tasks where organisation_id='00000000-0000-0000-0000-000000000001' and title='Provide children for each parent' and notes='Student names and links');
insert into public.tasks(organisation_id,title,notes,owner_name,priority,due_date,status) select '00000000-0000-0000-0000-000000000001','Provide year groups','Year group / date of birth','Students','high',current_date+4,'open' where not exists(select 1 from public.tasks where organisation_id='00000000-0000-0000-0000-000000000001' and title='Provide year groups' and notes='Year group / date of birth');
insert into public.tasks(organisation_id,title,notes,owner_name,priority,due_date,status) select '00000000-0000-0000-0000-000000000001','Provide days','Attendance days for Rudaina, Yazeed and Leena','Attendance','high',current_date+5,'open' where not exists(select 1 from public.tasks where organisation_id='00000000-0000-0000-0000-000000000001' and title='Provide days' and notes='Attendance days for Rudaina, Yazeed and Leena');
insert into public.tasks(organisation_id,title,notes,owner_name,priority,due_date,status) select '00000000-0000-0000-0000-000000000001','Provide day','Attendance day for Daniel Manu','Attendance','high',current_date+6,'open' where not exists(select 1 from public.tasks where organisation_id='00000000-0000-0000-0000-000000000001' and title='Provide day' and notes='Attendance day for Daniel Manu');
insert into public.tasks(organisation_id,title,notes,owner_name,priority,due_date,status) select '00000000-0000-0000-0000-000000000001','Provide day','Attendance day for C''yaan Amreen','Attendance','high',current_date+7,'open' where not exists(select 1 from public.tasks where organisation_id='00000000-0000-0000-0000-000000000001' and title='Provide day' and notes='Attendance day for C''yaan Amreen');
insert into public.tasks(organisation_id,title,notes,owner_name,priority,due_date,status) select '00000000-0000-0000-0000-000000000001','Confirm full names','Surnames for Aisha and Saif','Student names','medium',current_date+8,'open' where not exists(select 1 from public.tasks where organisation_id='00000000-0000-0000-0000-000000000001' and title='Confirm full names' and notes='Surnames for Aisha and Saif');
insert into public.tasks(organisation_id,title,notes,owner_name,priority,due_date,status) select '00000000-0000-0000-0000-000000000001','Confirm full names','Surnames for Rudaina, Yazeed and Leena','Student names','medium',current_date+9,'open' where not exists(select 1 from public.tasks where organisation_id='00000000-0000-0000-0000-000000000001' and title='Confirm full names' and notes='Surnames for Rudaina, Yazeed and Leena');
insert into public.tasks(organisation_id,title,notes,owner_name,priority,due_date,status) select '00000000-0000-0000-0000-000000000001','Provide staff record details','Assigned days, pay, DBS and training','Staff','high',current_date+10,'open' where not exists(select 1 from public.tasks where organisation_id='00000000-0000-0000-0000-000000000001' and title='Provide staff record details' and notes='Assigned days, pay, DBS and training');
insert into public.tasks(organisation_id,title,notes,owner_name,priority,due_date,status) select '00000000-0000-0000-0000-000000000001','Create when amount is known','Actual monthly invoice and payment records','Finance','high',current_date+11,'open' where not exists(select 1 from public.tasks where organisation_id='00000000-0000-0000-0000-000000000001' and title='Create when amount is known' and notes='Actual monthly invoice and payment records');
insert into public.tasks(organisation_id,title,notes,owner_name,priority,due_date,status) select '00000000-0000-0000-0000-000000000001','Provide exact checklist','Opening, closing and cleaning checklists','Operations','medium',current_date+12,'open' where not exists(select 1 from public.tasks where organisation_id='00000000-0000-0000-0000-000000000001' and title='Provide exact checklist' and notes='Opening, closing and cleaning checklists');
