#!/usr/bin/env node
/**
 * Writes config.js from environment variables at deploy time.
 * Static hosts (Render, Netlify, Vercel) run `npm run build` before publish.
 */
const fs = require('fs');
const path = require('path');

const provider = process.env.NOVA_PROVIDER || (process.env.SUPABASE_URL ? 'supabase' : 'mock');

const config = {
  provider,
  supabaseUrl: process.env.SUPABASE_URL || '',
  supabaseKey: process.env.SUPABASE_ANON_KEY || '',
  organisationId: process.env.NOVA_ORGANISATION_ID || '00000000-0000-0000-0000-000000000001'
};

const out = `// Generated by scripts/build-config.js — do not edit by hand in production.
window.NOVA_CONFIG = ${JSON.stringify(config, null, 2)};
`;

const target = path.join(__dirname, '..', 'config.js');
fs.writeFileSync(target, out, 'utf8');

console.log('Wrote config.js');
console.log('  provider:', config.provider);
console.log('  supabaseUrl:', config.supabaseUrl ? '(set)' : '(empty)');
console.log('  supabaseKey:', config.supabaseKey ? '(set)' : '(empty)');
console.log('  organisationId:', config.organisationId);
